#!/usr/bin/env python

from sys import argv
import fileinput

stopfile = open(argv[1])
stopwords = set(word.strip() for word in stopfile)
stopfile.close()
stopwords = stopwords.union(word.replace("'", '') for word in stopwords)

for line in fileinput.input(argv[2:]):
    tokens = line.split()
    print ' '.join(t for t in tokens if t not in stopwords)

